behaviors:
  CarAgent:
    trainer_type: ppo
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
