behaviors:
  CarTrainer1:
    trainer_type: ppo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
